/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=CloudflareEnv` (hash: 839f95b4c8c219b3ab68f36d868bfe84)
interface __BaseEnv_CloudflareEnv {
	BACKSTAGE_DB: D1Database;
	ASSETS: Fetcher;
	DEMO_FAULT: string;
	DEMO_SIGNING_KEY: string;
	DEMO_PASSCODE: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DEMO_FAULT" | "DEMO_SIGNING_KEY" | "DEMO_PASSCODE">> {}
}
