/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.sessions.jsonc --include-runtime=false --strict-vars=false --env-interface=SessionWorkerEnv worker-configuration.sessions.d.ts` (hash: 3ae0d968d483dc09b1b87d38d8c6ad29)
interface __BaseEnv_SessionWorkerEnv {
	SESSION_SLUG: string;
	SESSION_DOMAIN: string;
	SESSION_REPOSITORY_URL: string;
	SESSION_RUNTIME_SECRETS: string;
	SESSION_ACCESS_TEAM_DOMAIN: string;
	SESSION_ACCESS_PREVIEW_AUD: string;
	SESSION_ACCESS_EDITOR_AUD: string;
	Sandbox: DurableObjectNamespace<import("./src/session-worker").Sandbox>;
	SESSION_COORDINATOR: DurableObjectNamespace<import("./src/session-worker").SessionCoordinator>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/session-worker");
		durableNamespaces: "Sandbox" | "SessionCoordinator";
	}
	interface Env extends __BaseEnv_SessionWorkerEnv {}
}
interface SessionWorkerEnv extends __BaseEnv_SessionWorkerEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SESSION_SLUG" | "SESSION_DOMAIN" | "SESSION_REPOSITORY_URL" | "SESSION_RUNTIME_SECRETS" | "SESSION_ACCESS_TEAM_DOMAIN" | "SESSION_ACCESS_PREVIEW_AUD" | "SESSION_ACCESS_EDITOR_AUD">> {}
}
