/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.sessions.jsonc --include-runtime=false --strict-vars=false --env-interface=SessionWorkerEnv worker-configuration.sessions.d.ts` (hash: aaea56c8bac8f63bd8f6eebd1c6d0370)
interface __BaseEnv_SessionWorkerEnv {
	SESSION_SLUG: string;
	SESSION_DOMAIN: string;
	SESSION_REPOSITORY_URL: string;
	Sandbox: DurableObjectNamespace<import("./src/session-worker").Sandbox>;
	SESSION_COORDINATOR: DurableObjectNamespace<import("./src/session-worker").SessionCoordinator>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/session-worker");
		durableNamespaces: "Sandbox" | "SessionCoordinator";
	}
	interface Env extends __BaseEnv_SessionWorkerEnv {}
}
interface SessionWorkerEnv extends __BaseEnv_SessionWorkerEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SESSION_SLUG" | "SESSION_DOMAIN" | "SESSION_REPOSITORY_URL">> {}
}
