/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=CloudflareEnv` (hash: 054e9a86edd625e1ab8c93eac919a3f0)
interface __BaseEnv_CloudflareEnv {
	BACKSTAGE_DB: D1Database;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	ASSETS: Fetcher;
	DEMO_FAULT: string;
	DEMO_SIGNING_KEY: string;
	DEMO_PASSCODE: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DEMO_FAULT" | "DEMO_SIGNING_KEY" | "DEMO_PASSCODE">> {}
}
