/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.sessions.jsonc --include-runtime=false --strict-vars=false --env-interface=SessionWorkerEnv worker-configuration.sessions.d.ts` (hash: 0a289740c98e4cda109e95048a017813)
interface __BaseEnv_SessionWorkerEnv {
	Sandbox: DurableObjectNamespace<import("./src/session-worker").Sandbox>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/session-worker");
		durableNamespaces: "Sandbox";
	}
	interface Env extends __BaseEnv_SessionWorkerEnv {}
}
interface SessionWorkerEnv extends __BaseEnv_SessionWorkerEnv {}
